### ISSUE TITLE
2.9.2 no longer picks up builds in Enterprise

### ISSUE THREAD

**Issue by bnferguson** [travis-ci/worker#325]
We've seen a pattern recently with upgrades and fresh installs for Enterprise using 2.9.2 where it ends up commenting out the  `export TRAVIS_ENTERPRISE_BUILD_ENDPOINT="__build__"` line. As a result the worker can't receive the build scripts from `travis-build` and builds are not picked up. 

I'm not sure if it replaces all of the file or just edits this line. This file also contains our caching settings still for Enterprise as well as hostnames and passwords, so it feels like I would have heard about those going missing as well but I haven't heard anything so far. 

It seems uncommenting this line and restarting the server fixes the issue.

**Comment by meatballhat** [comment]
This has been fixed with subsequent releases, IIUC.  Please holler if you see otherwise ❤️

**Comment by schultyy** [comment]
Reopening this ticket, we still see that customers run into the problem that the worker doesn't pick up jobs after install. 
This is the installer we're currently using: 
https://raw.githubusercontent.com/travis-ci/worker/f0a29d8649bf372a46e91130d3b61649f6b5d88d/utils/install

**Comment by danishkhan** [comment]
The options described here: https://github.com/travis-ci/worker/blob/master/bin/travis-worker-install#L137 seem to not be doing anything. When I try to set the Enterprise host, security token, or specify that I'm setting it up for Enterprise and no AWS with `--enterprise` and `--aws` nothing actually gets set.

@meatballhat if you or someone can help guide us with doing some more debugging that be great. It seems that the `/etc/default/travis-enterprise` file gets set, but it's with all the default values and having all the variables commented out.

**Comment by bnferguson** [comment]
> The options described here: https://github.com/travis-ci/worker/blob/master/bin/travis-worker-install#L137 seem to not be doing anything.

Also worth noting that this happens even with our super old installer over at https://enterprise.travis-ci.com/install/worker. So I'm starting to wonder if something about how we packaged things changed which is why the build endpoint is always blocked out on new installs even when the other stuff gets setup correctly using this older installer. 

I'm trying to figure out where the change could have happened in the `/etc/default/travis-enterprise` but for some reason git shows the rename but acts like it's the first time its ever seen that file in https://github.com/travis-ci/worker/commits/master/packaging/overlay.d/common/etc/default/travis-enterprise

**Comment by bnferguson** [comment]
So this is strange, the commenting out of the build endpoint happened in Dec 2015: https://github.com/travis-ci/worker/commit/eabd2f7c1b3cbed8dfcfe81c3ab2b42a4d3fdee0#diff-6df2dafdf7470a418f801d7f34c020e8L7

But we didn't start seeing issues until June 2017 from what @danishkhan could find (Around 2.9.2?). Wondering what changed that'd suddenly cause this.

**Comment by danishkhan** [comment]
I looked on packagecloud to see how back of versions we have are. I installed [2.5.0](https://github.com/travis-ci/worker/tree/v2.5.0) which is from 2016 and that does everything fine and it doesn't comment out the build endpoint in the travis-enterprise file, so I'm really not sure what is going on where it is happening.

```
# Default ENV variables for Travis Enterprise
# Uncomment and set, then restart `travis-worker` for
# them to take effect.

export TRAVIS_ENTERPRISE_HOST="travis.hello.com"
export TRAVIS_ENTERPRISE_SECURITY_TOKEN="ssssssssssshhhhhhhhhhhhh"
export TRAVIS_ENTERPRISE_BUILD_ENDPOINT="__build__"
```

**Comment by meatballhat** [comment]
@danishkhan @bnferguson I'm sorry about the long delay.  Assuming there's still a problem with munging enterprise configs, are you able to open a separate issue for tracking that, or perhaps renaming and reopening this one?
