### ISSUE TITLE
State is not correctly updated after hard timeout for Linux jobs

### ISSUE THREAD

**Issue by bogdanap** [travis-ci/worker#379]
Worker version 3.0.2 doesn't update the state after a hard timeout is reached. 
The logs state that `The job exceeded the maximum time limit for jobs, and has been terminated`, but the job continues running.

After looking at the logs, it seems that the instances running the jobs are terminating properly, so this is strictly a state update issue.

Example job: https://travis-ci.org/joepvd/travis-experiment/builds/278560238

Example logs:
```
Sep 22 12:27:11 i-01032f5-production-2-worker-org-ec2 travis-worker: time="2017-09-22T10:27:05Z" level=info msg="running script" job_id=278560240 job_path="joepvd/travis-experiment/jobs/278560240" pid=1 processor="1e7cf5cf-3498-4818-b351-f22f4d5c84f5@1.i-01032f5-production-2-worker-org-ec2.travisci.net" repository="joepvd/travis-experiment" self="step_run_script"  
Sep 22 12:32:11 i-01032f5-production-2-worker-org-ec2 travis-worker: time="2017-09-22T10:32:02Z" level=info msg="hard timeout exceeded, terminating" job_id=278560240 job_path="joepvd/travis-experiment/jobs/278560240" pid=1 processor="1e7cf5cf-3498-4818-b351-f22f4d5c84f5@1.i-01032f5-production-2-worker-org-ec2.travisci.net" repository="joepvd/travis-experiment" self="step_run_script"  
Sep 22 12:32:11 i-01032f5-production-2-worker-org-ec2 travis-worker: time="2017-09-22T10:32:02Z" level=info msg="finishing job" job_id=278560240 job_path="joepvd/travis-experiment/jobs/278560240" pid=1 processor="1e7cf5cf-3498-4818-b351-f22f4d5c84f5@1.i-01032f5-production-2-worker-org-ec2.travisci.net" repository="joepvd/travis-experiment" self="amqp_job" state=errored  
Sep 22 12:32:11 i-01032f5-production-2-worker-org-ec2 travis-worker: time="2017-09-22T10:32:02Z" level=error msg="couldn't update job state" err="context deadline exceeded" job_id=278560240 job_path="joepvd/travis-experiment/jobs/278560240" pid=1 processor="1e7cf5cf-3498-4818-b351-f22f4d5c84f5@1.i-01032f5-production-2-worker-org-ec2.travisci.net" repository="joepvd/travis-experiment" self="step_run_script" state=errored  
Sep 22 12:32:11 i-01032f5-production-2-worker-org-ec2 travis-worker: time="2017-09-22T10:32:02Z" level=info msg="finished script" job_id=278560240 job_path="joepvd/travis-experiment/jobs/278560240" pid=1 processor="1e7cf5cf-3498-4818-b351-f22f4d5c84f5@1.i-01032f5-production-2-worker-org-ec2.travisci.net" repository="joepvd/travis-experiment" self="step_run_script"  
Sep 22 12:32:41 i-01032f5-production-2-worker-org-ec2 travis-worker: time="2017-09-22T10:32:34Z" level=info msg="stopped instance" job_id=278560240 job_path="joepvd/travis-experiment/jobs/278560240" pid=1 processor="1e7cf5cf-3498-4818-b351-f22f4d5c84f5@1.i-01032f5-production-2-worker-org-ec2.travisci.net" repository="joepvd/travis-experiment" self="step_start_instance"  
Sep 22 12:32:41 i-01032f5-production-2-worker-org-ec2 travis-worker: time="2017-09-22T10:32:34Z" level=info msg="finished job" job_id=278560240 job_path="joepvd/travis-experiment/jobs/278560240" pid=1 processor="1e7cf5cf-3498-4818-b351-f22f4d5c84f5@1.i-01032f5-production-2-worker-org-ec2.travisci.net" repository="joepvd/travis-experiment" self=processor  
```

**Comment by bogdanap** [comment]
This should be fixed by https://github.com/travis-ci/worker/pull/378

**Comment by mitchellkrogza** [comment]
@bogdanap issue still persisting 

![screen shot 2017-09-27 at 10 18 59 am](https://user-images.githubusercontent.com/9961541/30902928-6b758fc2-a36d-11e7-88a4-de0e49b8e78e.png)

**Comment by rusher** [comment]
thanks, that have fixed https://github.com/travis-ci/travis-ci/issues/8463

**Comment by mitchellkrogza** [comment]
@rusher lucky for you, all our jobs still running for 50+ minutes then killing themselves but still saying running.

**Comment by skirpichev** [comment]
> all our jobs still running for 50+

Same for me, e.g. [this](https://travis-ci.org/diofant/diofant/jobs/280346963).

**Comment by rusher** [comment]
False hope : some jobs that ended badly recently worked, but issue still exists : https://travis-ci.org/MariaDB/server/jobs/280349825

**Comment by mitchellkrogza** [comment]
@rusher it's indeed still rather broken

**Comment by mitchellkrogza** [comment]
And this was the reply I got from Travis support last night 

```
Hey there,

During the week of September 25th-29th, we’re at a company-wide offsite, working on new features and improving Travis CI. While we’ll be checking email daily, our response times may be delayed.
```

**Comment by solarce** [comment]
Hello,

I am sorry for any confusion, but the code we anticipate fixing this issue, in https://github.com/travis-ci/worker/pull/378, has not been merged or deployed to production, so the issue still exists for users.

The PR and this issue will be updated as we move towards getting this fix into production.

**Comment by mitchellkrogza** [comment]
@solarce i hope it's sooner than later. It's put a total stop to all my projects as not one of them works anymore, very frustrating. Please keep us updated.
